menu:
    About: /about/
    Contact: /contact/
    Tags: /tags/

# default creative commons license
# choose a license at https://creativecommons.org/choose/
cc: "by"

rss: "/atom.xml"

favicon: "/favicon.ico"

footer:
    - label: Categories
      link: /categories/
      icon: list
    - label: Archives
      link: /archives/
      icon: archive
