menu:
    About: /about/
    Contact: /contact/
    Tags: /tags/

footer:
    - label: Categories
      link: /categories/
      icon: list
    - label: Archives
      link: /archives/
      icon: archive
