excerpt_link: 阅读全部

menu:
    Tags: /tags/
    Contact: /contact/
    About: /about/

footer:
    - label: Categories
      link: /categories/
      icon: list
    - label: Archives
      link: /archives/
      icon: archive
