import hljs from 'highlight.js/lib/highlight';
import apache from 'highlight.js/lib/languages/apache';
import bash from 'highlight.js/lib/languages/bash';
import brainfuck from 'highlight.js/lib/languages/brainfuck';
import cpp from 'highlight.js/lib/languages/cpp';
import csharp from 'highlight.js/lib/languages/cs';
import erlang from 'highlight.js/lib/languages/erlang';
import ini from 'highlight.js/lib/languages/ini';
import java from 'highlight.js/lib/languages/java';
import javascript from 'highlight.js/lib/languages/javascript';
import json from 'highlight.js/lib/languages/json';
import lua from 'highlight.js/lib/languages/lua';
import makefile from 'highlight.js/lib/languages/makefile';
import objc from 'highlight.js/lib/languages/objectivec';
import php from 'highlight.js/lib/languages/php';
import processing from 'highlight.js/lib/languages/processing';
import python from 'highlight.js/lib/languages/python';
import scss from 'highlight.js/lib/languages/scss';
import tex from 'highlight.js/lib/languages/tex';
import xml from 'highlight.js/lib/languages/xml';
import yaml from 'highlight.js/lib/languages/yaml';

hljs.registerLanguage('apache', apache);
hljs.registerLanguage('apacheconfig', apache);
hljs.registerLanguage('bash', bash);
hljs.registerLanguage('brainfuck', brainfuck);
hljs.registerLanguage('cpp', cpp);
hljs.registerLanguage('csharp', csharp);
hljs.registerLanguage('css', scss);
hljs.registerLanguage('erlang', erlang);
hljs.registerLanguage('latex', tex);
hljs.registerLanguage('ini', ini);
hljs.registerLanguage('java', java);
hljs.registerLanguage('javascript', javascript);
hljs.registerLanguage('json', json);
hljs.registerLanguage('lua', lua);
hljs.registerLanguage('makefile', makefile);
hljs.registerLanguage('objc', objc);
hljs.registerLanguage('php', php);
// hljs.registerLanguage('plain', plain);
hljs.registerLanguage('processing', processing);
hljs.registerLanguage('python', python);
hljs.registerLanguage('scss', scss);
hljs.registerLanguage('tex', tex);
hljs.registerLanguage('xml', xml);
hljs.registerLanguage('yaml', yaml);

hljs.initHighlightingOnLoad();
